# Generated by Django 4.1.5 on 2023-02-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Категория'),
        ),
    ]
