# Generated by Django 4.1.6 on 2023-02-20 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default/placeholder.png', upload_to='product', verbose_name='Картинка'),
        ),
    ]
